#!/bin/bash
SOWFA_DURHAM()
{
   # Important locations.
   export inst_loc=/apps/applications/openfoam/6.20190620/1/default
   export spack_loc=/nopt/nrel/ecom/wind
   export sowfa_loc=$HOME/OpenFOAM/SOWFA-6

   # Load the right modules.
   echo "Purging and loading modules..."
   module purge
   module load openfoam/6.20190620
   module unload openmpi
   module unload gcc
   module load intel mkl openblas openmpi hdf5
   module list
   
   export OPENFOAM_VERSION=6
   
   # Unset OpenFOAM environment variables.
   if [ -z "$FOAM_INST_DIR" ]; then
      echo "Nothing to unset..."
   else
      echo "     *Unsetting OpenFOAM environment variables..."
      if [ -f "$FOAM_INST_DIR/OpenFOAM-$OPENFOAM_VERSION/etc/config.sh/unset" ]; then
         . $FOAM_INST_DIR/OpenFOAM-$OPENFOAM_VERSION/etc/config.sh/unset
      else
         . $FOAM_INST_DIR/OpenFOAM-$OPENFOAM_VERSION/etc/config/unset.sh
      fi
   fi

   # Set the OpenFOAM version and installation directory
   export OPENFOAM_VERSION=6
   export OPENFOAM_NAME=OpenFOAM-$OPENFOAM_VERSION
   export FOAM_INST_DIR=$inst_loc
   export WM_PROJECT_USER_DIR=/home/$USER/$USER-$OPENFOAM_VERSION
   export FOAMY_HEX_MESH=true
   
   # Source the OpenFOAM main environment.
   foamDotFile=$FOAM_INST_DIR/$OPENFOAM_NAME/etc/bashrc
   if [ -f $foamDotFile ] ; then
      echo "Sourcing $foamDotFile..."
      source $foamDotFile
   fi

   # For wmake compiling.
   export WM_NCOMPPROCS=24
   export WM_COLOURS="white blue green cyan red magenta yellow"

   # Alias to tutorials.
   alias tut='cd /home/$USER/OpenFOAM/$USER-$OPENFOAM_VERSION/tutorials'
   
   # Set the SOWFA installation directory.
   export SOWFA_DIR=$sowfa_loc
   export SOWFA_APPBIN=$SOWFA_DIR/platforms/$WM_OPTIONS/bin
   export SOWFA_LIBBIN=$SOWFA_DIR/platforms/$WM_OPTIONS/lib
   export OPENFAST_DIR=$HOME/OpenFOAM/openfast
   export LD_LIBRARY_PATH=$SOWFA_LIBBIN:$OPENFAST_DIR/lib:$LD_LIBRARY_PATH
   export PATH=$SOWFA_APPBIN:$OPENFAST_DIR/bin:$PATH
}
